Entity/Banner.php
<?php

namespace WebtownPhp\BannerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * Banner
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="WebtownPhp\BannerBundle\Entity\BannerRepository")
 */
class Banner
{
    const CONTENT_TYPE_HTML  = 'H';
    const CONTENT_TYPE_IMAGE = 'I';
    const CONTENT_TYPE_FLASH = 'F';

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    protected $name;

    /**
     * Clicked banner target URL
     *
     * @var string
     *
     * @ORM\Column(name="target", type="string", length=255, nullable=true, options={
     *          "comment": "Clicked banner target URL"})
     */
    protected $target;

    /**
     * Place name for banner
     *
     * @Assert\NotBlank()
     * @var string
     *
     * @ORM\Column(name="place", type="string", length=255, nullable=false, options={
     *  "comment": "Place name for banner"})
     */
    protected $place;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="content_type", type="string", length=1, nullable=false)
     */
    protected $contentType;

    /**
     * Display priority
     *
     * @var integer
     *
     * @ORM\Column(name="priority", type="integer", nullable=false, options={
     *  "comment": "Display priority"})
     */
    protected $priority;

    /**
     * Max No. of times banner can be displayed
     *
     * @var integer
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="max_display_count", type="integer", nullable=false, options={
     *  "comment": "Max No. of times banner can be displayed"})
     */
    protected $maxDisplayCount;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="start_at", type="datetime", nullable=true)
     */
    protected $startAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="end_at", type="datetime", nullable=true)
     */
    protected $endAt;

    /**
     * @var integer
     *
     * @ORM\Column(name="display_count", type="integer", nullable=false)
     */
    protected $displayCount;

    /**
     * @var integer
     *
     * @ORM\Column(name="click_count", type="integer", nullable=false)
     */
    protected $clickCount;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean", nullable=false)
     */
    protected $isActive;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="content", type="text", nullable=false)
     */
    protected $content;


    /**
     * ===========================================================================================
     *                       B E G I N   S E T T E R S   A N D   G E T T E R S
     */

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Banner
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set target
     *
     * @param string $target
     * @return Banner
     */
    public function setTarget($target)
    {
        $this->target = $target;

        return $this;
    }

    /**
     * Get target
     *
     * @return string 
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * Set place
     *
     * @param string $place
     * @return Banner
     */
    public function setPlace($place)
    {
        $this->place = $place;

        return $this;
    }

    /**
     * Get place
     *
     * @return string 
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Set priority
     *
     * @param integer $priority
     * @return Banner
     */
    public function setPriority($priority)
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * Get priority
     *
     * @return integer 
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Set maxDisplayCount
     *
     * @param integer $maxDisplayCount
     * @return Banner
     */
    public function setMaxDisplayCount($maxDisplayCount)
    {
        $this->maxDisplayCount = $maxDisplayCount;

        return $this;
    }

    /**
     * Get maxDisplayCount
     *
     * @return integer 
     */
    public function getMaxDisplayCount()
    {
        return $this->maxDisplayCount;
    }

    /**
     * Set startAt
     *
     * @param \DateTime $startAt
     * @return Banner
     */
    public function setStartAt($startAt)
    {
        $this->startAt = $startAt;

        return $this;
    }

    /**
     * Get startAt
     *
     * @return \DateTime 
     */
    public function getStartAt()
    {
        return $this->startAt;
    }

    /**
     * Set endAt
     *
     * @param \DateTime $endAt
     * @return Banner
     */
    public function setEndAt($endAt)
    {
        $this->endAt = $endAt;

        return $this;
    }

    /**
     * Get endAt
     *
     * @return \DateTime 
     */
    public function getEndAt()
    {
        return $this->endAt;
    }

    /**
     * Set displayCount
     *
     * @param integer $displayCount
     * @return Banner
     */
    public function setDisplayCount($displayCount)
    {
        $this->displayCount = $displayCount;

        return $this;
    }

    /**
     * Get displayCount
     *
     * @return integer 
     */
    public function getDisplayCount()
    {
        return $this->displayCount;
    }

    /**
     * Set clickCount
     *
     * @param integer $clickCount
     * @return Banner
     */
    public function setClickCount($clickCount)
    {
        $this->clickCount = $clickCount;

        return $this;
    }

    /**
     * Get clickCount
     *
     * @return integer 
     */
    public function getClickCount()
    {
        return $this->clickCount;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return Banner
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param string $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     *                       E N D   S E T T E R S   A N D   G E T T E R S
     * ===========================================================================================
     */

    /**
     * @return string
     */
    public function getTypeName()
    {
        if ($this->isImage()) {
            return 'image';
        } elseif ($this->isHTML()) {
            return 'html';
        } else {
            return 'flash';
        }
    }

    /**
     * Lejárt vagy elfogyott a megjelenítési keret
     *
     * @return bool
     */
    public function isExpired()
    {
        return ! is_null($this->getEndAt()) && $this->getEndAt() <= (new \DateTime()) ||
            $this->getMaxDisplayCount() <= $this->getDisplayCount();
    }

    /**
     * CTR
     *
     * @return float
     */
    public function getClickThroughRate()
    {
        return $this->getClickCount()/$this->getDisplayCount()*100;
    }

    /**
     * pause/continue
     */
    public function toggle()
    {
        $this->setIsActive(! $this->getIsActive());
    }

    /**
     * @return string
     */
    public function getContentType()
    {
        return $this->contentType;
    }

    /**
     * @param string $contentType
     */
    public function setContentType($contentType)
    {
        $this->contentType = $contentType;
    }

    /**
     * @return array
     */
    public static function getContentTypeChoices()
    {
        return [
            'content_type_flash' => self::CONTENT_TYPE_FLASH,
            'content_type_image' => self::CONTENT_TYPE_IMAGE,
            'content_type_html'  => self::CONTENT_TYPE_HTML,
        ];
    }

    /**
     * @Assert\Callback
     * @param ExecutionContextInterface $context
     */
    public function validateDates(ExecutionContextInterface $context)
    {
        $start = $this->getStartAt();
        $end = $this->getEndAt();
        if (isset($start, $end) && $end < $start)
        {
            $context->buildViolation('banner_start_end_interval_invalid')
                ->setTranslationDomain('WebtownPhpBannerBundle')
                ->atPath('startAt')
                ->atPath('endAt')
                ->addViolation();
        }
    }

    /**
     * @Assert\Callback
     * @param ExecutionContextInterface $context
     */
    public function validateMaxDisplayCount(ExecutionContextInterface $context)
    {
        if ($this->getMaxDisplayCount() < $this->getDisplayCount())
        {
            $context->buildViolation('invalid_max_display_count')
                ->setTranslationDomain('WebtownPhpBannerBundle')
                ->atPath('maxDisplayCount')
                ->addViolation();
        }
    }

    /**
     * @return bool
     */
    public function isFlash()
    {
        return $this->getContentType() === self::CONTENT_TYPE_FLASH;
    }

    /**
     * @return bool
     */
    public function isImage()
    {

Resources/views/Admin/list_action_banner_preview.html.twig
<a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('banner_preview', object) }}">
    <i class="fa fa-search-plus"></i>
    {{ "preview_action" | trans({}, "WebtownPhpBannerBundle") }}
</a>

Resources/views/Admin/list_action_preview.html.twig
<a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('preview', object) }}">
    <i class="fa fa-search-plus"></i>
    {{ "preview_action" | trans({}, "WebtownPhpBannerBundle") }}
</a>

Resources/views/Admin/list_action_toggle.html.twig
<a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('toggle', object) }}">
    <i class="fa fa-{{ (object.isActive ? "pause" : "play") }}-circle"></i>
    {{ (object.isActive ? "toggle_action_stop" : "toggle_action_start") | trans({}, "WebtownPhpBannerBundle") }}
</a>

Resources/views/Admin/list_item_content_types.html.twig
{% extends admin.getTemplate('base_list_field') %}

{% block field %}
    <i class="fa fa-youtube-play {% if (not object.isFlash) %}text-muted{% endif %}"></i>
    <i class="fa fa-file-image-o {% if (not object.isImage) %}text-muted{% endif %}"></i>
    <i class="fa fa-file-code-o  {% if (not object.isHtml) %}text-muted{% endif %}"></i>
{% endblock %}

Resources/views/Admin/list_item_status.html.twig
{% extends admin.getTemplate('base_list_field') %}

{% trans_default_domain "WebtownPhpBannerBundle" %}

{% block field %}
    {% if (object.isExpired) %}
        <i class="fa fa-eye-slash text-muted" title="{{ "banner.status.expired" | trans }}"></i>
    {% elseif (object.isActive) %}
        <i class="fa fa-eye text-success" title="{{ "banner.status.active" | trans }}"></i>
    {% else %}
        <i class="fa fa-ban text-muted" title="{{ "banner.status.stopped" | trans }}"></i>
    {% endif %}
{% endblock %}

Resources/views/Admin/preview.html.twig
{% extends "WebtownPhpBannerBundle:Admin:preview_base.html.twig" %}

{% trans_default_domain "WebtownPhpBannerBundle" %}

{% block content %}
{% if object.isFlash %}
<h3>{{ "content_name_flash" | trans }}</h3>
{{ object.content }}
{% endif %}

{% if object.isImage %}
<h3>{{ "content_name_image" | trans }}</h3>
<img src="{{ object.content }}" alt="" />
{% endif %}

{% if object.isHTML %}
<h3>{{ "content_name_html" | trans }}</h3>
{{ object.content }}
{% endif %}
{% endblock %}

Resources/views/Admin/preview_base.html.twig
{% block content %}{% endblock %}

Resources/views/Admin/show_content.html.twig
{% extends "@SonataAdmin/CRUD/base_show_field.html.twig" %}

{% block field %}
    {% if (object.isFlash) %}{{ object.content }}{% endif %}
    {% if (object.isImage) %}<img src="{{ object.content }}">{% endif %}
    {% if (object.isHtml) %}{{ object.content }}{% endif %}
{% endblock %}

Resources/views/Admin/show_delete_button.html.twig
<a class="sonata-action-element" href="{{ admin.generateObjectUrl('delete', object) }}"><i class="fa fa-trash"></i>
    {{ "show_action_delete" | trans({}, "WebtownPhpBannerBundle") }}
</a>